[versions]
netty = "4.1.89.Final"
junit = "5.9.2"


[libraries]
netty-common = { group = "io.netty", name = "netty-common", version.ref = "netty" }
netty-buffer = { group = "io.netty", name = "netty-buffer", version.ref = "netty" }
netty-codec = { group = "io.netty", name = "netty-codec", version.ref = "netty" }
netty-transport = { group = "io.netty", name = "netty-transport", version.ref = "netty" }

expiringmap = { group = "net.jodah", name = "expiringmap", version = "0.5.10" }

# Test dependencies
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }


[bundles]


[plugins]

