name: Deploy Snapshot
on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    uses: CloudburstMC/Network/.github/workflows/deploy.yml@3.0
    with:
      deploy-url: "https://repo.opencollab.dev/maven-snapshots/"
    secrets:
      DEPLOY_USERNAME: ${{ secrets.OPENCOLLAB_USERNAME }}
      DEPLOY_PASSWORD: ${{ secrets.OPENCOLLAB_PASSWORD }}
      PGP_SECRET: ${{ secrets.MAVEN_CENTRAL_SECRET }}
      PGP_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_PASSPHRASE }}
